refactored bundle name and namespace validation to avoid duplication …
chmjs/vue-cli-plugin-chameleon-bundle pull request #10
Opened 2019-06-12 12:58 UTC by jelenaa

refactored bundle name and namespace validation to avoid duplication and refactored  'vue add @nsoft/chameleon-bundle' command  so you have to forward token now => 'vue add @nsoft/chameleon-bundle ${authToken}'

Resolves #8

2019-06-12 13:35 UTC, Lanchi requested changes

2019-06-12 13:35 UTC, Lanchi commented on prompts.js
> +  } else {
Since we have a `return` statement inside `if`, no need for `else` block here.
Same goes for namespace validation.

2019-06-12 14:25 UTC, Lanchi approved these changes

2019-06-13 06:03 UTC, moahmo approved these changes

2019-06-13 06:12 UTC, merged